/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-gradient-to-tr',
    'from-gray-900',
    'via-gray-800',
    'to-black',
    'text-white/50',
    'font-bold',
    'text-xl',
    'text-sm',
    'my-4',
    'py-2',
    'px-3',
    'rounded-lg',
    'font-sans',
    'border-2',
    'border-gray-700',
    'ml-2',
    'p-3',
    'bg-gray-500',
    'text-white',
    'rounded-lg',
    'transition-transform',
    'transform',
    'hover:bg-gray-600',
    'active:scale-95',
    'p-4',
    'flex',
    'justify-center',
    'w-full',
    'text-white',
    'text-center',
    'max-w-xxl',
    'border',
    'border-gray-200',
    'rounded-lg',
    'shadow',
    'dark:bg-gray-800',
    'dark:border-gray-700',
    'overflow-hidden',
    'font-mono',
    'text-white/65',
    'md:w-1/2',
    'text-gray-500',
    'text-gray-300',
    'text-justify',
    'text-lg',
    'text-gray-500',
    'text-gray-300',
    'text-white',
    'mb-2',
    'grid',
    'grid-cols-1',
    'md:grid-cols-3',
    'lg:grid-cols-4',
    'gap-4',
    'ml-2',
    'p-3',
    'text-sm',
    'bg-gray-500',
    'text-white',
    'rounded-lg',
    'transition-transform',
    'transform',
    'hover:bg-gray-600',
    'active:scale-95',
  ],
  theme: {
    extend: {
      fontFamily: {
        asap: ["Asap", "sans-serif"]
      }
    },
  },
  plugins: [],

}